export {default as Main} from './Main.js';
export {default as DineInTakeOut} from './DineInTakeOut.js';
export {default as RegularPriority} from './RegularPriority.js';
export {default as ProdSelect} from './ProdSelect.js';
export {default as OrderSum} from './OrderSum.js';
export {default as ProdModal} from './ProdModal.js';
export {default as Checkout} from './Checkout.js';
export {default as Confirmation} from './Confirmation.js';
export {default as NotFound} from './NotFound.js';